image:
  file: Dockerfile
  
ports:
  - port: 8001
  
tasks:
  -  command: mkdir /workspace/my-gitpod-capacitor/logs                              &&
              touch /workspace/my-gitpod-capacitor/logs/gitpod-install-log.txt       &&
       
       
              echo "Starting .gitpod.yml installation" &>>  /workspace/my-gitpod-capacitor/logs/gitpod-install-log.txt     &&  
       
             

          
              echo "Starting Apache"                   &>>  /workspace/my-gitpod-capacitor/logs/gitpod-install-log.txt      &&   
              apachectl start                                                                                               &&
              gp await-port 8001                                                                                            && 
              gp preview $(gp url 8001)                                                                                     &&
              
              
              
              echo "Ending .gitpod.yml installation"  &>>   /workspace/my-gitpod-capacitor/logs/gitpod-install-log.txt    
              
              
     
